// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5ccb6418-4e67-4af7-a25b-c4fde3e42ad5";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


String firmware_version;
float pm10_0_val;
float pm1_0_val;
float pm2_5_val;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(firmware_version, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pm10_0_val, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pm1_0_val, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pm2_5_val, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
